Repository MoonMinJeong/PSS, pull requests merged in 2022-10, with the labels that each got.

#11 🔀 :: (#10) login modal 퍼블리싱
  src/assets/login/close.png
  src/assets/login/github.png
  src/assets/login/google.png
  src/assets/login/loginBackground.png
  src/components/login/Button.tsx
  src/components/login/LoginModal.tsx
Labels: 퍼블리싱

#9 🔀 :: (#8) 디자인 수정한대로 퍼블리싱 수정
  src/assets/dummy/profile.svg
  src/assets/heart.svg
  src/assets/index.tsx
  src/components/PostList.tsx
  src/components/post/PostCard.tsx
  src/components/post/PostList.tsx
  src/pages/index.tsx
  src/utils/translate.ts
Labels: 리팩토링, 수정

#14 🔀 :: (#13) 슬라이드 컨트롤러 추가
  package-lock.json
  package.json
  src/components/Filter.tsx
  src/components/SliderController.tsx
  src/pages/_app.tsx
  yarn.lock
Labels: 기능 추가

#15 🔀 :: (#7) 헤더 추가
  src/assets/arrow.svg
  src/assets/index.tsx
  src/components/Header.tsx
  src/components/common/DropdownItem.tsx
  src/pages/_app.tsx
Labels: 기능 추가

#19 🔀 :: (#12) 소개글 상세보기 퍼블리싱
  src/assets/postDetail/HeartIcon.tsx
  src/assets/postDetail/StarIcon.tsx
  src/assets/postDetail/arrow.svg
  src/assets/postDetail/downArrow.png
  src/assets/postDetail/meatballMenu.svg
  src/assets/postDetail/topArrow.png
  src/assets/view.svg
  src/components/post/PostCard.tsx
  src/components/postDetail/HeartButton.tsx
  src/components/postDetail/Participant.tsx
  src/components/postDetail/PostSummary.tsx
  src/components/postDetail/Profile.tsx
  src/components/postDetail/Rating.tsx
  src/components/postDetail/SideInfo.tsx
  src/components/postDetail/postComment/Comment.tsx
  src/components/postDetail/postComment/CommentButtonBox.tsx
  src/components/postDetail/postComment/CommentInput.tsx
  src/components/postDetail/postComment/Reply.tsx
  src/components/postDetail/postComment/ReplyManage.tsx
  src/pages/post-detail.tsx
Labels: 퍼블리싱
